//
//  MessagesViewController.swift
//  MessagesExtension
//
//  Created by jamesshih on 2017/4/11.
//  Copyright © 2017年 i-link. All rights reserved.
//

import UIKit
import Messages

class MessagesViewController: MSMessagesAppViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.
        
        // Use this method to configure the extension and restore previously stored state.
        print("ℹ️will become active")
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dissmises the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
        print("ℹ️did resign active")
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        // Use this method to trigger UI updates in response to the message.
        print("ℹ️did receive")
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
        print("ℹ️did start sending")
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
        print("ℹ️did cancel sending")
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }

    @IBAction func customBtnPressed(_ sender: Any) {
        //1. we need to get a hold of the conversation (message between participants)
        //2. insert a message (you cannot send the message yourself)
//        let text = "Hello, how are you today?"
//        activeConversation?.insertText(text, completionHandler: nil)
        
        let layout = MSMessageTemplateLayout()
        layout.image = #imageLiteral(resourceName: "ilink-logo")
        layout.imageTitle = "ilink.com Website"
        layout.imageSubtitle = "Source code for iOS games and apps"
        layout.caption = "go check it out"
        
        layout.trailingCaption = "trailing caption"
        layout.trailingSubcaption = "trailing subcaption"
        
        layout.mediaFileURL = URL(string: "http://www.i-link.tw/")
        
        let message = MSMessage()
        message.layout = layout
        
        activeConversation?.insert(message, completionHandler: nil)
    }
    
}



















